version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: engineering-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: P@ssword123
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./database:/data  # Mount the database folder to access uniqueUsers.json and mongodb.js
    networks:
      - mongo-network

volumes:
  mongo-data:
    driver: local

networks:
  mongo-network:
    driver: bridge
